---
- name: Install Mysql package
  apt: name={{ item }} state=present
  with_items:
   - mysql-server

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  notify: 
  - restart mysql

- name: Install python-mysqldb
  apt: name=python-mysqldb state=present
